version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dashboard-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dashboard_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: dashboard-api
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql://root:root@db:3306/dashboard_db
      PORT: 3000
    command: >
      sh -c "
        npx prisma migrate dev --name init --skip-seed &&
        npx prisma generate &&
        npm run build &&
        npm start
      "

volumes:
  db-data:
